name: cnn-chloro
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - torchvision
  - hydra-core
  - numpy
  - xarray
  - pandas
  - matplotlib
  - dask
  - netcdf4
  - statsmodels
  - scikit-learn
  - cmocean
  - colorcet
  - omegaconf
