params:
    model : CNN
    rateDropout : 0.2
    val_split : 0.2
    lr : 0.001
    batch_size : 8
    n_epochs : 300
    random_state : stratify #42 #None

data:
    input  : obs
    output : obs_cci #obs_globcolour, globcolour_cmems
    sensor : GSM #VIR MER, MOD_, OLA, SWF
    d1_train : 2002-01
    d2_train : 2009-12
    d1_pred: 1993-01
    d2_pred: 2020-12
    d1_test: 2011-01
    d2_test: 2020-12
    plot_date: 2017-01
    lat_min : -50
    lat_max : 50
    lon_min : -180
    lon_max : 180
    var_input : ['sla','sst','ssr','u10','v10','u','v','mdt'] #obs

out:
    training : True
    prediction : True
    metric : True
    plot : True
   

path:
    log : ${hydra:run.dir}/ #new one
